import { readFile } from 'node:fs/promises';
import { defineConfig } from 'vite';

import { TASK_SUPABASE_SDK_SOURCE, buildTaskRuntimeEnv } from './scripts/sync-spa-assets.mjs';

// Two files the embedded Tasks app loads at runtime are generated by the build into dist and
// are deliberately not committed: the vendored Supabase browser bundle that app.html has
// pointed at since fd6e704, and env.json. The dev server serves the SOURCE tree, where
// neither exists, so both 404 and Tasks stops on
// "Auth service is unavailable. Configuration unavailable: Supabase SDK retry failed."
// while the same commit is fine in production — sdk-loader retries the same missing URL and
// reports the retry, which hides the plain 404 underneath it.
//
// Serve them here from the SAME definitions scripts/sync-spa-assets.mjs uses for the build.
// Reading the key from those definitions rather than restating it is the point: the host app
// and Tasks share an origin, so if they resolve different Supabase projects they hold
// different sessions and the embedded module bounces to the host login forever.
function taskRuntimeDevAssets() {
  return {
    name: 'quest-task-runtime-dev-assets',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const pathname = (req.url || '').split('?')[0];
        if (pathname === '/taskmanagement/vendor/supabase/supabase.js') {
          readFile(TASK_SUPABASE_SDK_SOURCE).then((sdk) => {
            res.setHeader('Content-Type', 'application/javascript; charset=utf-8');
            // Never cached in dev: the build serves this immutably under a ?v= release, and a
            // stale dev copy would survive a dependency change with no way to notice.
            res.setHeader('Cache-Control', 'no-store');
            res.end(sdk);
          }, next);
          return;
        }
        if (pathname === '/taskmanagement/env.json') {
          try {
            const env = `${JSON.stringify(buildTaskRuntimeEnv(), null, 2)}\n`;
            res.setHeader('Content-Type', 'application/json; charset=utf-8');
            res.setHeader('Cache-Control', 'no-store');
            res.end(env);
          } catch (error) {
            next(error);
          }
          return;
        }
        next();
      });
    },
  };
}

export default defineConfig({
  plugins: [taskRuntimeDevAssets()],
  base: process.env.GITHUB_PAGES === 'true' ? '/quest-hq-command-center/' : '/',
  define: {
    // The fallback is a 40-character placeholder, not a short word, so a local
    // build measures the same bundle size as a deployed one. With 'development'
    // (11 chars) the entry chunk came out ~33 gzip bytes smaller than production,
    // which let the bundle-budget gate pass locally and then fail the deploy.
    // Must be high-entropy hex, not a repeated character: gzip crushes a run of
    // identical bytes to almost nothing, so '0'.repeat(40) measured the same as the
    // old short word and defeated the point.
    __QUEST_BUILD_SHA__: JSON.stringify(process.env.VERCEL_GIT_COMMIT_SHA || process.env.GIT_COMMIT_SHA || 'a3f5c81d94b2e07f6c15d8a29b34e7016f8c2d5b'),
  },
  build: {
    manifest: true,
    rollupOptions: {
      output: {
        manualChunks(id) {
          const normalizedId = id.replaceAll('\\', '/');
          if (
            normalizedId.endsWith('/src/workspaces/plugin-catalog.js')
            || normalizedId.endsWith('/src/workspaces/tenant-route.js')
            || normalizedId.endsWith('/src/communications/sms-readiness.js')
            || normalizedId.endsWith('/src/ui/workspace-loading.js')
            || normalizedId.endsWith('/src/ui/lazy-surface-error.js')
          ) {
            return 'workspace-runtime';
          }
          if (!id.includes('node_modules')) return undefined;
          if (id.includes('@supabase')) return 'vendor-supabase';
          return undefined;
        },
      },
    },
  },
  server: {
    fs: {
      allow: ['..']
    }
  }
});
