// Tabler -> Phosphor name map.
//
// Phosphor names things by the object, where Tabler names them by the action: a
// magnifying glass rather than `search`, an envelope rather than `mail`, a house rather
// than `home`, a gear rather than `settings`. That accounts for most of this table —
// these are not obscure icons, they are the most common ones in the app.
//
// Only names that neither match verbatim nor resolve through the Lucide table need an
// entry. Anything still unresolved keeps its Tabler glyph, which is far better than a
// confidently wrong icon.
//
// `-filled` maps to the plain glyph: the fill weight is a separate Phosphor font, and
// mixing two weights inside one pack would look like a mistake rather than a choice.
//
// Every target is validated against Phosphor's own selection.json at build time.

export const PHOSPHOR_ALIASES = {
  // the systematic differences
  search: 'magnifying-glass',
  mail: 'envelope',
  'mail-filled': 'envelope',
  home: 'house',
  'home-filled': 'house',
  settings: 'gear',
  'settings-filled': 'gear',
  'chevron-down': 'caret-down',
  'chevron-up': 'caret-up',
  'chevron-left': 'caret-left',
  'chevron-right': 'caret-right',
  message: 'chat-circle',
  'message-2': 'chat-circle',
  'message-filled': 'chat-circle',
  'message-circle': 'chat-circle',
  'message-plus': 'chat-circle-dots',
  messages: 'chats-circle',
  dots: 'dots-three',
  'grip-vertical': 'dots-six-vertical',
  edit: 'pencil-simple',
  bolt: 'lightning',
  send: 'paper-plane-tilt',

  // status and feedback
  'alert-triangle': 'warning',
  'alert-triangle-filled': 'warning',
  'alert-circle': 'warning-circle',
  'alert-circle-filled': 'warning-circle',
  'help-circle': 'question',
  'circle-check': 'check-circle',
  'circle-check-filled': 'check-circle',
  'circle-x': 'x-circle',
  'circle-plus': 'plus-circle',
  'circle-dot': 'record',
  'square-x': 'x-square',
  'arrow-right-circle': 'arrow-circle-right',
  ban: 'prohibit',
  'eye-off': 'eye-slash',
  loader: 'spinner',
  'loader-2': 'spinner-gap',
  progress: 'spinner',
  activity: 'pulse',
  history: 'clock-counter-clockwise',
  restore: 'clock-counter-clockwise',
  refresh: 'arrows-clockwise',
  rotate: 'arrow-clockwise',
  'arrow-back-up': 'arrow-u-up-left',
  'arrow-forward-up': 'arrow-u-up-right',
  'arrow-move-right': 'arrow-right',
  'arrows-minimize': 'arrows-in-simple',
  'arrows-sort': 'arrows-down-up',
  selector: 'caret-up-down',
  select: 'cursor',
  click: 'cursor-click',
  'external-link': 'arrow-square-out',
  unlink: 'link-break',
  sparkles: 'sparkle',
  logout: 'sign-out',
  login: 'sign-in',
  pin: 'push-pin',
  route: 'path',
  timeline: 'chart-line',
  versions: 'stack',
  'window-maximize': 'corners-out',

  // files and documents
  checkbox: 'check-square',
  'list-check': 'list-checks',
  'clipboard-check': 'clipboard-text',
  'clipboard-list': 'clipboard-text',
  'clipboard-data': 'clipboard-text',
  'clipboard-plus': 'clipboard-text',
  forms: 'clipboard-text',
  template: 'layout',
  'file-certificate': 'certificate',
  'file-check': 'file-text',
  'file-export': 'export',
  'file-import': 'download-simple',
  'file-invoice': 'receipt',
  'file-pencil': 'file-text',
  'file-spreadsheet': 'file-xls',
  'folder-share': 'folder-simple-star',
  'package-import': 'package',
  packages: 'stack-simple',
  box: 'package',
  braces: 'brackets-curly',
  'letter-case': 'text-aa',
  'letter-t': 'text-t',
  'math-function': 'function',
  report: 'file-text',
  'report-analytics': 'chart-bar',
  'database-export': 'database',
  'device-floppy': 'floppy-disk',
  inbox: 'tray',
  tags: 'tag',
  badges: 'seal-check',
  'rosette-discount-check': 'seal-check',
  award: 'medal',
  'award-filled': 'medal',
  'trash-x': 'trash',

  // layout
  'layout-dashboard': 'squares-four',
  'layout-grid': 'squares-four',
  'layout-grid-add': 'squares-four',
  'layout-cards': 'cards',
  'layout-board-split': 'columns',
  apps: 'squares-four',

  // filters
  filter: 'funnel',
  'filter-off': 'funnel-x',
  'filter-search': 'funnel',

  // people and places
  'id-badge': 'identification-badge',
  'id-badge-2': 'identification-card',
  id: 'identification-card',
  'user-question': 'user-focus',
  'building-community': 'buildings',
  'building-skyscraper': 'buildings',
  'building-bank': 'bank',
  'building-store': 'storefront',
  school: 'graduation-cap',
  map: 'map-trifold',
  'current-location': 'crosshair',
  'heart-handshake': 'handshake',

  // objects
  cash: 'money',
  server: 'hard-drives',
  'cloud-upload': 'cloud-arrow-up',
  photo: 'image',
  'photo-up': 'image',
  paint: 'paint-brush',
  'paint-filled': 'paint-brush',
  brush: 'paint-brush',
  ballpen: 'pen',
  droplet: 'drop',
  'droplet-filled': 'drop',
  plane: 'airplane',
  bike: 'bicycle',
  ship: 'boat',
  forklift: 'truck',
  puzzle: 'puzzle-piece',
  'puzzle-filled': 'puzzle-piece',
  'plug-connected': 'plug',
  'tools-kitchen-2': 'fork-knife',
  'settings-automation': 'gear-six',
  automation: 'flow-arrow',
  music: 'music-note',
  'calendar-event': 'calendar-blank',
  'calendar-stats': 'calendar-check',
  'calendar-up': 'calendar-plus',
  // The spreadsheet ribbon. Phosphor is the only pack with true insert-row/column glyphs.
  'layout-align-top': 'align-top',
  'layout-align-middle': 'align-center-vertical',
  'layout-align-bottom': 'align-bottom',
  'letter-a': 'text-aa',
  'arrow-autofit-width': 'arrows-merge',
  'row-insert-top': 'rows-plus-top',
  'row-insert-bottom': 'rows-plus-bottom',
  'column-insert-left': 'columns-plus-left',
  'column-insert-right': 'columns-plus-right',
  'row-remove': 'rows',
  'column-remove': 'columns',
  'ruler-measure': 'ruler',
  'file-spreadsheet': 'file-xls',
  paint: 'paint-bucket',
  // `table` for both Insert and Delete would draw the two buttons identically.
  'table-plus': '',
  'table-minus': '',
  'border-all': '',
  'border-none': '',
  'letter-case-upper': '',
  'letter-case-lower': '',
  decimal: '',
  // Phosphor prefixes its text controls with `text-`.
  bold: 'text-b',
  italic: 'text-italic',
  underline: 'text-underline',
  'align-center': 'text-align-center',
  'align-right': 'text-align-right',
  // `text-align-justify` is justification, not wrapping. Two different things.
  'text-wrap': '',
};
