// Tabler -> Remix Icon name map.
//
// Remix names every glyph with a style suffix — `home-line` and `home-fill` are separate
// entries. The build tries `<name>-line` first, so a Tabler name that matches Remix's stem
// needs no entry here. This table is for the stems that differ.
//
// Targets are written WITHOUT the suffix; the build appends `-line`, falling back to
// `-fill` for the handful Remix only draws filled. That keeps the pack a single visual
// weight instead of mixing outline and solid at random.
//
// Anything unresolved keeps its Tabler glyph. Every target is validated against Remix's
// own glyph map at build time.

export const REMIX_ALIASES = {
  // navigation and chrome
  'chevron-down': 'arrow-down-s',
  'chevron-up': 'arrow-up-s',
  'chevron-left': 'arrow-left-s',
  'chevron-right': 'arrow-right-s',
  'caret-down-filled': 'arrow-down-s',
  'caret-up-filled': 'arrow-up-s',
  selector: 'expand-up-down',
  dots: 'more',
  'grip-vertical': 'draggable',
  x: 'close',
  plus: 'add',
  minus: 'subtract',
  'circle-plus': 'add-circle',
  'circle-check': 'checkbox-circle',
  'circle-check-filled': 'checkbox-circle',
  'circle-x': 'close-circle',
  'circle-dot': 'record-circle',
  'circle-dashed': 'checkbox-blank-circle',
  'square-x': 'close-circle',
  checks: 'check-double',
  checklist: 'list-check-3',
  'list-details': 'list-check-2',
  list: 'list-unordered',
  'arrow-up-right': 'arrow-right-up',
  'arrow-move-right': 'arrow-right',
  'arrow-back-up': 'arrow-go-back',
  'arrow-forward-up': 'arrow-go-forward',
  'arrows-minimize': 'collapse-diagonal',
  'window-maximize': 'expand-diagonal',
  rotate: 'clockwise',
  logout: 'logout-box-r',
  login: 'login-box',
  ban: 'forbid',
  unlink: 'link-unlink',
  click: 'cursor',
  select: 'cursor',
  pin: 'pushpin',
  sparkles: 'sparkling',
  timeline: 'line-chart',
  versions: 'stack',
  'layout-dashboard': 'dashboard',
  'layout-kanban': 'kanban-view',
  'layout-board-split': 'layout-column',
  point: 'circle',

  // status
  'alert-triangle': 'error-warning',
  'alert-triangle-filled': 'error-warning',
  'alert-circle': 'alert',
  'alert-circle-filled': 'alert',
  'help-circle': 'question',
  'info-circle': 'information',
  activity: 'pulse',
  heartbeat: 'heart-pulse',
  bolt: 'flashlight',
  power: 'shut-down',

  // people
  users: 'group',
  'users-group': 'group',
  'users-plus': 'group',
  'user-plus': 'user-add',
  'user-check': 'user-follow',
  'user-circle': 'account-circle',
  'address-book': 'contacts-book',
  crown: 'vip-crown',
  'heart-handshake': 'shake-hands',
  signature: 'quill-pen',

  // documents
  'clipboard-check': 'clipboard',
  'clipboard-list': 'clipboard',
  'clipboard-data': 'clipboard',
  'clipboard-text': 'clipboard',
  'clipboard-plus': 'clipboard',
  forms: 'survey',
  template: 'layout',
  notes: 'sticky-note',
  books: 'book-2',
  files: 'file-copy',
  copy: 'file-copy',
  'file-certificate': 'award',
  'file-export': 'file-upload',
  'file-import': 'file-download',
  'file-invoice': 'bill',
  'file-pencil': 'file-edit',
  'file-spreadsheet': 'file-excel',
  'folder-share': 'folder-shared',
  'folder-plus': 'folder-add',
  'database-export': 'database-2',
  'package-import': 'inbox-archive',
  packages: 'stack',
  box: 'box-3',
  package: 'box-3',
  paperclip: 'attachment',
  tag: 'price-tag-3',
  tags: 'price-tag-3',
  badges: 'verified-badge',
  'rosette-discount-check': 'verified-badge',
  'trash-x': 'delete-bin',
  trash: 'delete-bin',
  highlight: 'mark-pen',
  ballpen: 'ball-pen',
  'letter-case': 'font-size-2',
  'letter-t': 'text',
  hash: 'hashtag',
  sum: 'functions',
  'math-function': 'functions',
  'currency-dollar': 'money-dollar-circle',
  'credit-card': 'bank-card',
  'credit-card-filled': 'bank-card',

  // charts
  'chart-bar': 'bar-chart',
  'chart-line': 'line-chart',
  'chart-pie': 'pie-chart',
  'chart-pie-filled': 'pie-chart',
  'report-analytics': 'bar-chart-box',

  // messaging
  message: 'message-3',
  'message-circle': 'chat-1',
  'message-plus': 'chat-new',
  messages: 'chat-3',
  send: 'send-plane',
  'phone-call': 'phone',
  headset: 'headphone',
  headphones: 'headphone',
  'headphones-filled': 'headphone',

  // time
  clock: 'time',
  'clock-hour-4': 'time',
  'clock-filled': 'time',
  'calendar-stats': 'calendar-check',
  'calendar-plus': 'calendar-event',
  'calendar-up': 'calendar-event',

  // devices and objects
  'device-desktop': 'computer',
  'device-laptop': 'macbook',
  'cloud-upload': 'upload-cloud-2',
  adjustments: 'equalizer',
  'adjustments-filled': 'equalizer',
  'adjustments-horizontal': 'equalizer-2',
  automation: 'flow-chart',
  'plug-connected': 'plug',
  coffee: 'cup',
  pill: 'capsule',
  paw: 'footprint',
  droplet: 'drop',
  'droplet-filled': 'drop',
  flame: 'fire',
  'fire-extinguisher': 'fire',
  'photo-up': 'image-add',
  'current-location': 'focus-3',

  // buildings and trades
  'building-warehouse': 'building',
  'building-bank': 'bank',
  'building-factory': 'building-4',
  // Remix has no site-trade glyphs — no helmet, shovel, ladder, crane or brick wall. These
  // keep their Tabler icon rather than borrowing something vaguely similar: `hard-drive`
  // for a hard hat would mislabel the control, which is worse than one mixed icon.
  helmet: '',
  bulldozer: '',
  crane: '',
  ladder: '',
  wall: '',
  shovel: '',
  forklift: 'truck',
  'tools-kitchen-2': 'restaurant',
};
